name: Docker Build

on:
  push:
    branch: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - id: login-ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - id: docker-metadata
      uses: docker/metadata-action@v3
      with:
        images: library/ubuntu:20.04@sha256:8ae9bafbb64f63a50caab98fd3a5e37b3eb837a3e0780b78e5218e63193961f9
        tags: ${{ steps.build-tags.outputs.tags }}
        labels: |
          org.opencontainers.image.title=Containerized GitHub Runner
          org.opencontainers.image.vendor=GitHub
          org.opencontainers.image.version=latest
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.description=
          org.opencontainers.image.authors=Mark Ferrell
          org.opencontainers.image.source=https://github.com/major0/gh-ecs-runner.git
          org.opencontainers.image.url=https://github.com/major0/gh-ecs-runner
          org.opencontainers.image.base.name=docker.com/library/ubuntu
          org.opencontainers.image.base.digest=sha256:8ae9bafbb64f63a50caab98fd3a5e37b3eb837a3e0780b78e5218e63193961f9

    - id: build-push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/major0/gh-ecs-runner:latest
        labels: ${{ steps.docker-metadata.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/major0/gh-ecs-runner:latest
        cache-to: type=inline
